from tkinter import *
root=Tk()
def add():
      a=float(e1.get())
      b=float(e2.get())
      print(a+b)
e1=Entry(root)
e1.pack()
e2=Entry(root)
e2.pack()
b1=Button(root,text="Add",command=add)
b1.pack()
def sub():
      c=float(e3.get())
      d=float(e4.get())
      print(c-d)
e3=Entry(root)
e3.pack()
e4=Entry(root)
e4.pack()
b2=Button(root,text="Sub",command=sub).pack()
def mul():
      a1=float(e5.get())
      b2=float(e6.get())
      print(a1*b2)
e5=Entry(root)
e5.pack()
e6=Entry(root)
e6.pack()
b3=Button(root,text="Mul",command=mul).pack()
def div():
      a2=float(e7.get())
      b2=float(e8.get())
      print(a2/b2)
e7=Entry(root)
e7.pack()
e8=Entry(root)
e8.pack()
b4=Button(root,text="Div",command=div).pack()
b5=Button(root,text="Exit",command=root.quit)
b5.pack()    
root.mainloop()