# username , mobile,age,password,conformpass,email,buttun(login,conform)
from tkinter import *
root=Tk()
L1=Label(root,text="User name")
e1=Entry()
L2=Label(root,text="Mobile number")
e2=Entry()
L3=Label(root,text="Age")
e3=Entry()
L4=Label(root,text="Password")
e4=Entry()
L5=Label(root,text="Conform Password")
e5=Entry()
L6=Label(root,text="Email")
e6=Entry()
L1.grid(row=0,column=0)
e1.grid(row=0,column=1)
L2.grid(row=1,column=0)
e2.grid(row=1,column=1)
L3.grid(row=2,column=0)
e3.grid(row=2,column=1)
L4.grid(row=3,column=0)
e4.grid(row=3,column=1)
L5.grid(row=4,column=0)
e5.grid(row=4,column=1)
L6.grid(row=5,column=0)
e6.grid(row=5,column=1)
bt=Button(root,text="Login",fg="red",bg="green")
bt1=Button(root,text="Conform",fg="red",bg="green")
bt.grid(row=6,column=0)
bt1.grid(row=6,column=1)
root.mainloop()