# Generated by Django 4.2.7 on 2023-11-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
